name: Build and Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Backend
        run: npm ci

      - name: Build Backend
        working-directory: ./Backend
        run: npm run build

  notify:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend] # Wait for both jobs to finish
    steps:
      - name: Send custom message to User 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.ACCESS_TOKEN }}
          message: |
            Commit done in repo BTP-V1 ( 🔒 SURAKSHA SETU 🌉).

            Commit message: ${{ github.event.head_commit.message }}

            Committer: ${{ github.actor }}

            Commit URL: ${{ github.event.head_commit.url }}

            Frontend Build Status: ${{ needs.build-frontend.result }}  

            Backend Build Status: ${{ needs.build-backend.result }}

      - name: Send custom message to User 2
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.HARSH_CHAT_ID }}
          token: ${{ secrets.ACCESS_TOKEN }}
          message: |
            Commit done in repo BTP-V1 ( 🔒 SURAKSHA SETU 🌉).

            Commit message: ${{ github.event.head_commit.message }}

            Committer: ${{ github.actor }}

            Commit URL: ${{ github.event.head_commit.url }}

            Frontend Build Status: ${{ needs.build-frontend.result }}  

            Backend Build Status: ${{ needs.build-backend.result }}
