name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: Send custom message to User 1
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.ACCESS_TOKEN }}
        message: |
          Commit done in repo BTP-V1 , do pull before commiting anything new to avoid
          git conflicts ( unless u like to enjoy solving bugs 🪲).
          Commit message: ${{ github.event.head_commit.message }}
          Committer: ${{ github.actor }}
          Commit URL: ${{ github.event.head_commit.url }}

    - name: Send custom message to User 2
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.HARSH_CHAT_ID }}
        token: ${{ secrets.ACCESS_TOKEN }}
        message: |
          Commit done in repo BTP-V1 , do pull before commiting anything new to avoid
          git conflicts ( unless u like to enjoy solving bugs 🪲).
          Commit message: ${{ github.event.head_commit.message }}
          Committer: ${{ github.actor }}
          Commit URL: ${{ github.event.head_commit.url }}
